version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - mynetwork

  web:
    build: .
    ports:
      - "5000:5000"

    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ite@db001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:


