version: '3.8'
services:

  web:
    build: .
    ports:
      - "5001:5000"

    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ite@db001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: reaksamai8899@gmail.com
      PGADMIN_DEFAULT_PASSWORD: me@123
    ports:
      - "5050:5050"
    networks:
      - mynetwork
      
networks:
  mynetwork:


