version: "3.1"
services:
  web:
    build: web
    restart: always
    ports: -5000:5000
    environment:
      - DEBUG=1
    networks:
      - app_network
  proxy:
    build: proxy
    restart: always
    ports: 
      -80:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
